{{- range $externalSecret := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ $externalSecret.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: templated
          serviceAccountRef:
            name: {{ $externalSecret.name }}
            namespace: {{ $externalSecret.namespace }}
{{- end }}