{{- range $externalSecret := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ $externalSecret.namespace }}
spec:
  secretStoreRef:
    name: {{ $externalSecret.name }}
    kind: ClusterSecretStore
  target:
    name: vault-{{ $externalSecret.name }}
  data:
  {{- range $secret := $externalSecret.secrets }}
  - secretKey: {{ $secret.secretKey }}
    remoteRef:
      key: {{ $secret.key }}
      property: {{ $secret.property }}
  {{ end }}
{{- end }}
